labelPRBasedOnFilePath:
  "Dependencies 📦":
    - Dockerfile*
    - composer.*
    - package.json
    - package-lock.json
    - yarn.lock
  "Docker 🐳":
    - Dockerfile*
    - .docker/**/*
  "Image 🖼":
    - *.gif
    - **/*.gif
    - *.jpg
    - **/*.jpg
    - *.jpeg
    - **/*.jpeg
    - *.png
    - **/*.png
    - *.webp
    - **/*.webp
  "CSS 👩‍🎨":
    - *.css
    - **/*.css
  "HTML 👷‍♀️":
    - *.htm
    - **/*.htm
    - *.html
    - **/*.html
  "NEON 🦹‍♂️":
    - *.neon
    - **/*.neon
  "MarkDown 📝":
    - *.md
    - **/*.md
  "YAML 🍄":
    - *.yml
    - **/*.yml
    - *.yaml
    - **/*.yaml
  "JSON 👨‍💼":
    - *.json
    - **/*.json
  "Go 🐹":
    - *.go
    - **/*.go
  "JavaScript 🦏":
    - *.js
    - **/*.js
    - package.json
    - package-lock.json
    - yarn.lock
  "PHP 🐘":
    - *.php
    - **/*.php
    - composer.*
  "Configuration ⚙":
    - .github/*
  "CI 🚧":
    - .github/workflows/*
  "Templates 🌲":
    - *.twig
    - **/*.twig
    - *.tpl
    - **/*.tpl
  "Helm ☸":
    - .helm/**/*
  "Tests 🧪":
    - tests/**/*
  "Source 🔮":
    - src/**/*

labelerFlags:
    labelOnPRUpdates: true
